### PR TITLE
Add OpenCV version of inspect

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by kaworu** [comment]
Hello @yamt and thanks for the PR. Visually I find the result quite different from `inspect`, is that expected?
2021-05-02-220715_1920x1080_scrot
2021-05-02-220729_1920x1080_scrot

**Comment by yamt** [comment]
> Hello @yamt and thanks for the PR. Visually I find the result quite different from `inspect`, is that expected?
> 2021-05-02-220715_1920x1080_scrot
> 2021-05-02-220729_1920x1080_scrot

i haven't used sdl version at all.

when i was developing this, i was using quite large images. (like 12M pixels)
it might explain the larger annotations.

if you provide some pairs of qr code images and sdl screenshots, i can try to mimic them closely.

**Comment by yamt** [comment]
the last push is just a conflict resolution

**Comment by yamt** [comment]
the last push fixed crashes in pixelColor().

**Comment by yamt** [comment]
@kaworu ping?

**Review by kaworu — APPROVED** [review]
Sorry, was offline for a time. The image I used for the screenshot above was https://github.com/kaworu/node-quirc/raw/master/test/data/Hello%2BWorld.png. Diff LGTM, not fundamentally opposed to have opencv visually rendering differently from SDL but IMHO a little consistency would be nice to have.

**Comment by dlbeer** [comment]
I agree that it would be nice for them to be consistent, but it looks ok for now -- thanks!

**Pull request merged**
