### PR TITLE
Use clock_gettime() instead of clock()

### PR DESCRIPTION
**Pull request by czarkoff**
`clock()` function provides approximation of processor time used, measured in "*clocks*". Amount of clocks per second varies between 100 (Minix, NetBSD, OpenBSD), 128 (DragonFly BSD, FreeBSD, older versions of MacOS X), 1000 (Windows) and 1000000 (Linux, newer versions of MacOS X, Solaris).  The range of these numbers make conversion to milliseconds (the unit of display in `qrtest`) problematic.  Ie. current implementation of conversion macro leads to division by zero on platforms with less then 1000 "clocks" per second.  `clock_gettime()` function with its nanosecond values appears to be a better and more portable alternative to clock().

### CODE REVIEW

**Comment by dlbeer** [comment]
I think this is a good idea, but doesn't tv_nsec hold only the number of nanoseconds since the last second boundary? I don't expect that the operations we're timing to take longer than a second under normal circumstances, but if the time crosses a second-boundary, the rollover on tv_nsec would lead to an incorrect value. A small wrapper function to calculate (tv_sec * 1000000000 + tv_nsec) would give you the monotonic counter you need.

**Comment by czarkoff** [comment]
I failed to take rollover into account.

I guess a macro will do here.  FWIW it would make sense to convert `timespec` to milliseconds and store the result in unsigned integer (or in `uint32_t` if quirk is targeting 16-bit architectures).  This would eliminate conversion macro that is used to print values.

**Comment by dlbeer** [comment]
On Sun, Aug 14, 2016 at 02:32:03PM -0700, Dmitrij D. Czarkoff wrote:
> I failed to take rollover into account.
> 
> I guess a macro will do here.  FWIW it would make sense to convert `timespec` to milliseconds and store the result in unsigned integer (or in `uint32_t` if quirk is targeting 16-bit architectures).  This would eliminate conversion macro that is used to print values.

Yep, sounds good to me. Let me know once you have something implemented
and I'll be happy to merge it.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by czarkoff** [comment]
It didn't take long...

**Pull request merged**
