### PR TITLE
Added a mode for devices with low stack memory using dinamic memory.

### PR DESCRIPTION
**Pull request by guardiola98**
I have added an option of using dynamic memory in most of the arrays used on the library, using a macro, which is defined in quirc.h. 
In order to check if all dynamic memory i have used, has been freed, i have used Valdgrind (https://valgrind.org/docs/manual/mc-manual.html).
Once I have checked all that, i have created a macro, in order to don't modify your code if the macro LOW_STACK_MODE is undefined.

### CODE REVIEW

**Comment by dlbeer** [comment]
Sorry, but I can't accept this. Reasons are:

  * This change pretty much replaces entire files by changing the formatting and breaking the 80-column limit.
  * The calls to malloc() are not checked, and there is no way to return an error code to the user in cases of memory allocation failure.
  * I'm not convinced that there's a good use case for this (but I might be wrong). Can you think of a system where stack memory is limited, but dynamic allocation is available and reliable?

**Comment by guardiola98** [comment]
About your reasons:

- I understand that maybe i have changed a lot the files without knowing because i was just trying to reach a quirc functional library with less than 6KB stack usage, I can clone the library again and change the minimum lines as posible.

- You are right about that i have not cheched the calls to malloc(), i have to implement that.

- I'm working in a project, using an ESP32, where I am limited to use 6KB of stack memory for each thread, and I am not allowed to increase that value. This has a reason and it is because we have many threads running and it could be a problem using more of 6KB of stack for each of those threads. Besides this, an ESP32 based board can include extra RAM (PSRAM) but it can't be used as a stack memory.

As an additional information, i have been working, in order to change the recursive flood_fill_seed() to an iterative version and I have had good results. This version of that function, is activated when the LOW_STACK_MODE is defined. I have achieved my objective of a quirc functional library that uses less tha 6KB. The next step to me is to check the malloc() calls, and try to change less all the files. When i have all done, i will done another pull request.

Finally, I want to add that I will understand if you don't accept my pool request because seems to be intrusive on your code.

Regards, Josep.

**Comment by dlbeer** [comment]
On Tue, Jun 16, 2020 at 12:41:44PM -0700, guardiola98 wrote:
> As an additional information, i have been working, in order to change the recursive flood_fill_seed() to an iterative version and I have had good results. This version of that function, is activated when the LOW_STACK_MODE is defined. I have achieved my objective of a quirc functional library that uses less tha 6KB. The next step to me is to check the malloc() calls, and try to change less all the files. When i have all done, i will done another pull request.

Hi Josep,

I think this modification alone (an iterative version of flood fill)
would be worth considering if you can make it reliable and efficient.
The existing flood fill algorithm isn't great and could use improvement.

I'm still not convinced that using malloc() inside the function calls is
a great idea, because you have no means of reporting it to the user
unless you change the ABI, which I would very much like to avoid.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by xdissent** [comment]
FWIW this fixed my WASM build on iOS, which currently suffers from a bug that drastically limits the stack. :heart:

**Comment by kAworu** [comment]
Marking at `wontfix` for now because there are multiple concern about the patch. As it stand, the formatting and design (unchecked malloc) issues are blocking.

**Review by zengshu — APPROVED** [review]

**Pull request closed without merging**
